### ISSUE TITLE
string instead of unsigned char?

### ISSUE THREAD

**Issue by shokarta** [SergeyBel/AES#15]
Hello,

how do I load the:
`unsigned char *innew = aes.DecryptCBC(out, BLOCK_BYTES_LENGTH, key, iv);`
with out, key and iv as string (QString ideally) and not as unsigned char?
usage like this makes it highly dificult to use

**Comment by SergeyBel** [comment]
I don't think it is a good idea. AES algorithm requires exactly unsigned char for correctness but conversion between `string` and `unsigned char *` may be unsafe

**Comment by VaasKahnGrim** [comment]
While this has been a while, why would string to unsigned char * be unsafe? Cause I'd imagine even if its unsafe there would be a way to force it to be safe.

With how commonly used std::string is I'd imagine it being a major loss to not be able to use this lib with std::string
