### ISSUE TITLE
question on input lenght

### ISSUE THREAD

**Issue by johann50** [SergeyBel/AES#18]
In the README.md, 
had a question on the the data input length passed into EncryptECB.
You have there

       unsigned int plainLen = 16 * sizeof(unsigned char);  //bytes in plaintext

Should the length be number of  bits or bytes ?   Also have same question regarding the length of data  passed into  DecryptECB.

Thanks.

**Comment by SergeyBel** [comment]
This is length in bytes. C++ `sizeof` operator returns size in bytes. 16 is length of `plain` array. Same answer for `DecryptECB` method
