### ISSUE TITLE
class variable in constructor is bytes or bits ?

### ISSUE THREAD

**Issue by johann50** [SergeyBel/AES#19]
In the constructor the following is no of bits not bytes:

 blockBytesLen = 4 * this->Nb * sizeof(unsigned char);

**Comment by SergeyBel** [comment]
`keyLen` parameter in constructor can be one of the three values: 128, 192, 256 (key length in bits). 
`$this->Nb` always equals 4, so `4 * this->Nb * sizeof(unsigned char)` is a length in bytes (not bits) of one AES block
