### ISSUE TITLE
AES::PaddingNulls memory leak

### ISSUE THREAD

**Issue by lukasz95** [SergeyBel/AES#2]
Hi,
Thanks for the AES implementation. But in AES::PaddingNulls method I've probably found memory leak and mistake. In AES.CPP at line 121 you create new array and allocate memory for it. In next line you copy input array into it and then do nothing with new array. It cause a memory leak as well because of no memory deallocate.
Regards

**Comment by SergeyBel** [comment]
Hi, thanks, this is fixed in ec25c027e85d2aed6648d892e1227f04f08206d8
