### ISSUE TITLE
wrong result

### ISSUE THREAD

**Issue by naweednri** [SergeyBel/AES#20]
for values below, it has to be "a8daf85bb9fca12ee0670e5deec04665" but it gives wrong result
key: 44e343953ea1281397174b150c7ac711
iv: 3b2db82fa18ed03b79877f45af9396f0
input: dddad64392c2634ab8c098a0be625b07
aes.DecryptCBC(input, 4, key,iv);

**Comment by SergeyBel** [comment]
Do you use AES-128 mode? I tried AES(128) and answer is right "a8daf85bb9fca12ee0670e5deec04665"

```c++
AES aes(128);
unsigned char key[]={0x44,0xe3,0x43,0x95,0x3e,0xa1,0x28,0x13,0x97,0x17,0x4b,0x15,0x0c,0x7a,0xc7,0x11};
unsigned char iv[]={0x3b,0x2d,0xb8,0x2f,0xa1,0x8e,0xd0,0x3b,0x79,0x87,0x7f,0x45,0xaf,0x93,0x96,0xf0};
unsigned char input[]={0xdd,0xda,0xd6,0x43,0x92,0xc2,0x63,0x4a,0xb8,0xc0,0x98,0xa0,0xbe,0x62,0x5b,0x07};
unsigned char *output = aes.DecryptCBC(input, 16, key,iv);
```
