### ISSUE TITLE
Usage questions

### ISSUE THREAD

**Issue by VaasKahnGrim** [SergeyBel/AES#21]
So I'm trying to figure out how to use this in order to encrypt and decrypt file contents. For my use case some files could be as large as 10mb in size and some could be below that. I'm currently storying the file contents as "const char* file_contents"

I'm trying to get a wrapper function setup for handling encryption/decryption.

```c++
const char* Cryptor_Wrapper(int mode,const char* code_key,const char* file_contents){
	char* output;

	if(mode == 1){
		// Encrypt file_contents and return it as output
	}else{
		// Decrypt file_contents and return it as output
	}
	return output;
}
```

I want to be able to use the int variable in order to be able to choose between decrypting or encrypting and being able to pass in a key with the file_contents.

however I'm currently looking at the test.cpp file and I'm a little confused on how to properly use EAS-256-CBC to occomplish this. I was wondering if I could get some help with figuring out what I need to use in my wrapper function exactly

**Comment by SergeyBel** [comment]
If you want use AES-256-CBC just use `EncryptCBC` for encryption and `DecryptCBC` for decryption in 256 AES mode 

```c++
AES aes(256);
aes.EncryptCBC(...);
```

see detailed examples in tests
