### ISSUE TITLE
Encryption is extremly slow

### ISSUE THREAD

**Issue by Bit00009** [SergeyBel/AES#23]
Hi why this library takes so long time to encrypt compared to other libs like crypto++ or .Net AESCrypter ?
am I doing something wrong ?

input file is only 30MB and it takes 54 sec to encrypt...
```CPP
unsigned int encSize = 0;

	LOG("Encrypting...")
	auto encrypted_ptr = aes.EncryptCBC(outdata.data(), outdata.size(), key, iv, encSize);

	LOG("Writing to disk...")
	fout.open("encryptedfile", ios::binary | ios::out);
	fout.write((char*)encrypted_ptr, encSize);
	fout.close();
```

**Comment by SergeyBel** [comment]
Hi
I've optimized the code a bit. Currently encryption for 30M file takes 3-4 seconds on my machine
