### ISSUE TITLE
Compilation warning "comparison of integer expressions of different signedness"

### ISSUE THREAD

**Issue by BullyWiiPlaza** [SergeyBel/AES#29]
The following code produces a warning about comparing integer expressions of different signedness:
```
void AES::printHexArray(unsigned char a[], unsigned int n) {
	for (int i = 0; i < n; i++) { // <--
		printf("%02x ", a[i]);
	}
}
```
The fix is to simply declare `i` as an `unsigned int`.

**Comment by SergeyBel** [comment]
What command do you use to compile?

**Comment by BullyWiiPlaza** [comment]
I use `GCC` with the command line flags `-Wall` and `-Wextra` which enable more warnings than you get by default.

**Comment by SergeyBel** [comment]
Fixed in https://github.com/SergeyBel/AES/pull/30
