### ISSUE TITLE
How to use this class in my code

### ISSUE THREAD

**Issue by VinayIsHere** [SergeyBel/AES#32]
Hy @SergeyBel Thanks for this class, Actually i want encrypt some video files before streaming and after streaming in the destination end I want to decrypt those files, Can you please tell me how can I use your class in my program to encrypt a single file. Can you show some test code example. I checked your ```tests.cpp``` but it's very confusing I am not getting from where you are taking file as input.

So see in order to use your class, First I need to clone this repository and after that i should include your header ```AES.h``` asnd ```AES.cpp``` in my project, Now suppose I have one file ```file.mp4``` can you show some sample how can I encrypt this file. I need some code example where you include your ```.h``` and ```.cpp``` files and use it to encrypt the file.

**Comment by Flone-dnb** [comment]
Have you seen README.md?
Anyway, here is how I use it to encrypt a message string:

```
    // Encrypt message.

    char* pRawMessage = new char[message.length() * 2 + 1];
    memset(pRawMessage, 0, message.length() * 2 + 1);

    std::memcpy(pRawMessage, message.c_str(), message.length() * 2);

    unsigned int iEncryptedMessageSize = 0;
    unsigned char* pEncryptedMessageBytes = pAES->EncryptECB(reinterpret_cast<unsigned char*>(pRawMessage),
                                                             static_cast<unsigned int>(message.length() * 2 + 1),
                                                             reinterpret_cast<unsigned char*>(vSecretAESKey),
                                                             iEncryptedMessageSize);
```
Although in your case it's not a good thing to load the whole video file into the memory. @SergeyBel is there a way to encrypt without loading the whole thing into memory?

**Comment by SergeyBel** [comment]
This class encrypts an array of  `unsigned char`. The answer to the original question is to convert the video to `unsigned char*` and encrypt. If the file is very large then you can encrypt it block by block

**Comment by saumyashah7** [comment]
Referring to the code above I am trying to encrypt and decrypt a string. With normal string, I do not get any trouble but if I try to use a number like "1" as a string sometimes it goes through and other times it gives an exception. Here is the sample code:

```
   AES* pAES=new AES(128);
    //string message = "Action123";
    string message = "123";
    cout << "String: "<< message << "\n";
    
    unsigned char vSecretAESKey[] =   { 0x00, 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08, 0x09, 0x0a, 0x0b, 0x0c, 0x0d, 0x0e, 0x0f };
    char* pRawMessage = new char[message.length()  + 1];
    memset(pRawMessage, 0, message.length()  + 1);
    std::memcpy(pRawMessage, message.c_str(), message.length()  + 1);

    unsigned int iEncryptedMessageSize = 0;
    unsigned char* pEncryptedMessageBytes = pAES->EncryptECB(reinterpret_cast<unsigned char*>(pRawMessage),
        static_cast<unsigned int>(message.length()  + 1),
        reinterpret_cast<unsigned char*>(vSecretAESKey),
        iEncryptedMessageSize);
    cout << "Encrypted Hex: "; pAES->printHexArray(pEncryptedMessageBytes, message.length() + 1);
    cout << "\n";
    cout << "Encrypted String: "; pAES->printCharArray(pEncryptedMessageBytes, message.length()  + 1);
    


    unsigned char* pDecryptedMessageBytes = pAES->DecryptECB(reinterpret_cast<unsigned char*>(pEncryptedMessageBytes),
        static_cast<unsigned int>(message.length()  + 1),
        reinterpret_cast<unsigned char*>(vSecretAESKey));
    cout << "\n";
    cout << "Decrypted Hex: "; pAES->printHexArray(pDecryptedMessageBytes, message.length()  + 1);
    cout << "\n";
    cout << "Decrypted String: "; pAES->printCharArray(pDecryptedMessageBytes, message.length()  + 1);
    
    delete pAES;
    delete[] pRawMessage;
    delete[] pEncryptedMessageBytes;
    delete[] pDecryptedMessageBytes;
```
Also while releasing memory for pDecryptedMessageBytes, I get error "HEAP CORRUPTION DETECTED". not sure why.

**Comment by saumyashah7** [comment]
Never mind. Fixed it using:

` const unsigned int BLOCK_BYTES_LENGTH = 16 * sizeof(unsigned char);`
