### ISSUE TITLE
How to know the decrypted buffer size?

### ISSUE THREAD

**Issue by BullyWiiPlaza** [SergeyBel/AES#33]
Let's say I receive an encrypted buffer via some source like a file on the file system or a server and I don't know the decrypted size. If I decrypt it using e.g. `unsigned char *AES::DecryptCBC(unsigned char in[], unsigned int inLen, unsigned char key[], unsigned char *iv)` I get a heap allocated buffer with the same length as `inLen` but none of the parameters indicate the output length.

If we take a look at [how `Java` handles this](https://www.baeldung.com/java-aes-encryption-decryption), we can see that `cipher.final()` returns a byte array which includes its length, even on decryption of a buffer of an unknown decrypted size so it is definitely possible.

Since this is a `C++` library it would be great if we could get some modernization like returning a `std::string` or so as return value since it also includes the length automatically.

**Comment by Flone-dnb** [comment]
The returned buffer has null char in the end if I'm not mistaken. So you can read until 0 (or just std::string(pDecryptedBuffer)).
You can also use math to calculate the size of the decrypted buffer (just google something like "aes decrypt size").

**Comment by BullyWiiPlaza** [comment]
> The returned buffer has null char in the end if I'm not mistaken. So you can read until 0 (or just std::string(pDecryptedBuffer)).

That is actually false, the buffer is non-initialized so it doesn't necessarily contain 0 bytes:
`unsigned char* decrypted_buffer = new unsigned char[inLen];`
Also wrapping the buffer into a `std::string(pDecryptedBuffer)` as you suggested only works if the decrypted buffer's length is correctly determined by `strlen(pDecryptedBuffer) + 1` which will not work due to the blockwise decryption adding garbage `UTF-8` characters at the end (this happened in my case).

> You can also use math to calculate the size of the decrypted buffer (just google something like "aes decrypt size").

I researched a bit but didn't get a definitive answer. If there is a definite way of knowing the exact output buffer size it would still be great to have as part of the library in some way. I solved this issue for my purpose by implementing a hack of detecting the last character of my plaintext but it doesn't generalize for all inputs.

**Comment by SergeyBel** [comment]
It is very simple - decrypted buffer size equals encrypted buffer size.  
For example size of decrypted buffer after using `unsigned char *AES::DecryptCBC(unsigned char in[], unsigned int inLen, unsigned char key[], unsigned char *iv)`  will be `inLen`  (of course `inLen` must be equal to an integer number of blocks)

**Comment by BullyWiiPlaza** [comment]
> It is very simple - decrypted buffer size equals encrypted buffer size.

The decrypted buffer is indeed allocated as large as the input buffer but the "actual" decrypted buffer size is not necessarily in multiples of the block size since AES allows you to encrypt any sized data to begin with. The padding bytes to fill up until a multiple of the block size are then **not** supposed to be part of the decrypted data.

For clarification, let me show you this code example:

```
AES aes(128);
unsigned char plain_text[] = {0x44, 0x55, 0x66, 0x77, 0x00}; // Not a multiple of the block size!
unsigned char key[] = {0x00, 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08, 0x09, 0x0a, 0x0b, 0x0c, 0x0d, 0x0e,
					   0x0f};
unsigned int cipher_text_length = 0;
const auto cipher_text = aes.EncryptECB(plain_text, sizeof(plain_text), key, cipher_text_length);
const auto decrypted_text = aes.DecryptECB(cipher_text, cipher_text_length, key);

printf("Plain text: ");
aes.printHexArray(plain_text, sizeof(plain_text));
printf("\n");
printf("Cipher text: ");
aes.printHexArray(cipher_text, cipher_text_length);
printf("\n");
printf("Decrypted text: ");
aes.printHexArray(decrypted_text, cipher_text_length); // Assuming inLen == outLen
printf("\n");

assert(memcmp(decrypted_text, plain_text, sizeof(plain_text)) == 0);
assert(BLOCK_BYTES_LENGTH == cipher_text_length);

delete[] cipher_text;
```
Output:
```
Plain text: 44 55 66 77 
Cipher text: 56 0c 78 6f 46 c1 ad ff 93 72 2d 04 ec 41 f6 38 
Decrypted text: 44 55 66 77 00 00 00 00 00 00 00 00 00 00 00 00
```
Here you can see that `plain_text` is not a multiple of the block size, therefore I expect to be able to figure out its actual size (5 in this case) after decryption without needing to store `sizeof(plain_text)` somewhere. Instead, my decrypted buffer size is rounded up to the next multiple of the block size (16 in this case) which is wrong since the decrypted data is only length 5. It is impossible to know whether `plain_text` was length `4` or `5` if you append or remove the null byte since `decrypted_text` will look identical in both scenarios. This makes the usage of this library problematic without always providing an input data with a length of a multiple of the block size.

**Comment by SergeyBel** [comment]
This library encrypt and decrypt data by AES specification. Padding is not part of specification. So decrypt function can not detect "actual" decrypted size, it only decrypts message block by block. 
This library simply add nulls at the end of message for padding but you can use any padding you want. Just apply your padding to message before encrypt and after decrypt
