### ISSUE TITLE
using namespace std

### ISSUE THREAD

**Issue by PaulJohnson1** [SergeyBel/AES#51]
Not all users of the library will want to be forced to use the std namespace when implementing this library. They will be forced to either switch to another library or edit the source code.

**Comment by inriz-com-tom** [comment]
I agree 100%.

**Comment by tom16384** [comment]
Yes. using namespace std; is terrible!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
