### ISSUE TITLE
not found to_string

### ISSUE THREAD

**Issue by T-Nosaka** [SergeyBel/AES#70]
Depends on std::string in CheckLength function of AES.cpp.
I think that std::string should be included in AES.h.
In VisualStudio 2022, I seem to get a compilation error.

AES.h

```
#ifndef _AES_H_
#define _AES_H_

#include <stdio.h>

// #include <cstring> <-- Remove
#include <string>   <---- add
#include <iostream>
#include <vector>
```

**Comment by SergeyBel** [comment]
it is wrong to delete `cstring` header
`string` header was added in https://github.com/SergeyBel/AES/commit/deafd370eb93de4aaf114ebf68f2917e769946eb

**Comment by T-Nosaka** [comment]
thank you!!
Compiled successfully.
