### ISSUE TITLE
Always encrypt 16 characters

### ISSUE THREAD

**Issue by ChangMuChen** [SergeyBel/AES#8]
Always encrypt 16 characters

**Comment by SergeyBel** [comment]
Can you please describe the problem in more detail and write code example

**Comment by ChangMuChen** [comment]
I cut a long string into segments of 16 characters each, then encrypt them one by one, then concatenate them into ciphertext, and then decrypt them in reverse.It works, but it doesn't make sense.

**Comment by ChangMuChen** [comment]
> 您能否更详细地描述问题并编写代码示例

I cut a long string into segments of 16 characters each, then encrypt them one by one, then concatenate them into ciphertext, and then decrypt them in reverse.It works, but it doesn't make sense.

**Comment by ChangMuChen** [comment]
> Can you please describe the problem in more detail and write code example

I cut a long string into segments of 16 characters each, then encrypt them one by one, then concatenate them into ciphertext, and then decrypt them in reverse.It works, but it doesn't make sense.

**Comment by ChangMuChen** [comment]
> Can you please describe the problem in more detail and write code example



> > Can you please describe the problem in more detail and write code example
> 
> I cut a long string into 16-character segments, encrypt them one by one, connect them to the ciphertext, and decrypt them backwards.It's doable, but is it reasonable?

code example:
[https://github.com/ChangMuChen/C-/tree/master/encodedecode](url)

**Comment by SergeyBel** [comment]
You can use method `EncryptECB` for strings with arbitary length

**Comment by ChangMuChen** [comment]
EncryptECB is ok，thank you~
