### ISSUE TITLE
EncryptCBC no add nulls to last block

### ISSUE THREAD

**Issue by nefton** [SergeyBel/AES#9]
AES aes(256);
std::string message = "hi master, how are your aes doing?";
unsigned char iv[] = { 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff };
unsigned char key[] = { 0x00, 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08, 0x09, 0x0a, 0x0b, 0x0c, 0x0d, 0x0e, 0x0f, 0x10, 0x011,
		0x12, 0x13, 0x14, 0x15, 0x16, 0x17, 0x18, 0x19, 0x1a, 0x1b, 0x1c, 0x1d, 0x1e, 0x1f };

unsigned int len;
unsigned char *out = aes.EncryptCBC((unsigned char*)message.c_str(), message.size(), key, iv, len);

this is error, because mesage length % 32 != 0;

outLen = GetPaddingLength(inLen){
{
  return (len / blockBytesLen) * blockBytesLen;
}
so GetPaddingLength(36) [with block = 32] = 32.
should input be filled by 0 for 64 length.

**Comment by SergeyBel** [comment]
Thank you for the detailed description. There was a bug in padding, it was fixed in https://github.com/SergeyBel/AES/pull/12
